name: SonarCloud

on:
  push:
    branches: [ main ] # Exécute l'action lors des push sur la branche main
#  pull_request:
#    branches: [ main ] # Exécute l'action lors des pull requests ciblant la branche main
#  workflow_dispatch: # Permet de déclencher l'action manuellement depuis l'interface GitHub

jobs:
  sonar_cloud:
    runs-on: windows-latest # Utilisation d'un environnement Windows pour .NET
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Remplacez par la version souhaitée de .NET

      - name: Afficher le répertoire courant
        run: pwd
        
      - name: Lister le contenu du répertoire
        run: Get-ChildItem .
      
      - name: Restauration des dépendances
        run: dotnet restore ./src/ConsoleApp/ConsoleApp.csproj

      #- name: Build de la solution
      #  run: dotnet build --configuration Release

      - name: Analyse statique avec SonarCloud CLI
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Vous devrez configurer ce secret dans GitHub
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Facultatif, si votre instance SonarCloud est différente
